#!/usr/bin/env bash
#
# bootstrap-local.sh — write local Terraform tfvars for both envs from your AWS CLI defaults.
#
# Idempotent: safe to run repeatedly. AWS EKS needs far fewer identifiers than the old OCI setup —
# Terraform authenticates from your ambient AWS credentials (`aws configure` / SSO / env vars) and
# the module defaults cover everything else. This just stamps a region into the gitignored
# terraform/envs/{staging,production}/terraform.tfvars so a re-apply is reproducible; edit the file
# afterwards if you want a non-default node size / VPC CIDR.
#
# Prereqs: the `aws` CLI, configured (`aws configure` or an SSO/role profile).
#
# Usage:
#   scripts/bootstrap-local.sh
#
# Optional env overrides:
#   AWS_PROFILE   AWS CLI profile to read the region from   (default: the CLI's active profile)
#   TELOS_REGION  override the region                       (default: `aws configure get region`)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

die() { echo "error: $*" >&2; exit 1; }

command -v aws >/dev/null 2>&1 || die "the 'aws' CLI is not on PATH — install it and run 'aws configure'"

REGION="${TELOS_REGION:-$(aws configure get region || true)}"
[ -n "$REGION" ] || REGION="us-east-1"
echo "==> region: $REGION"

# Sanity-check credentials so a misconfigured CLI fails here, not mid-apply.
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  echo "  warn: 'aws sts get-caller-identity' failed — configure the AWS CLI before 'terraform apply'." >&2
fi

# Per-env VPC CIDRs (must not overlap if you ever peer them). Matches the variables.tf defaults.
declare -A CIDR=( [staging]="10.10.0.0/16" [production]="10.20.0.0/16" )

write_tfvars() {
  local env="$1" out="$REPO_ROOT/terraform/envs/$1/terraform.tfvars"
  cat > "$out" <<EOF
# GENERATED by scripts/bootstrap-local.sh — re-run the script instead of hand-editing (or edit freely;
# it is gitignored). Terraform auth comes from your AWS CLI environment, not from here.
region             = "$REGION"
cluster_version    = "1.30"
vpc_cidr           = "${CIDR[$env]}"
node_instance_type = "t4g.large" # t4g.xlarge (16 GB) if the LGTM stack OOMs
node_ami_type      = "AL2023_ARM_64_STANDARD"
EOF
  echo "  wrote $out"
}

echo "==> Writing tfvars"
write_tfvars staging
write_tfvars production

cat <<EOF

Done. Next (see RUNBOOK.md for the full path):
  0. (once) create the S3 state bucket named in backend.tf (native S3 locking; no DynamoDB table)
  1. cd terraform/envs/staging && terraform init && terraform apply
  2. aws eks update-kubeconfig --name telos-staging --region $REGION
  3. apply k8s/addons + secrets, then: kustomize build k8s/overlays/staging | kubectl apply -f -
EOF
