apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: telosmud

resources:
  - ../../base
  - ingress.yaml

images:
  - name: ghcr.io/OWNER/telos-world
    newName: ghcr.io/double-nibble/telos-world
    newTag: latest
  - name: ghcr.io/OWNER/telos-gate
    newName: ghcr.io/double-nibble/telos-gate
    newTag: latest
  - name: ghcr.io/OWNER/telos-account
    newName: ghcr.io/double-nibble/telos-account
    newTag: latest
  - name: ghcr.io/OWNER/telos-migrate
    newName: ghcr.io/double-nibble/telos-migrate
    newTag: latest
  - name: ghcr.io/OWNER/telos-seed
    newName: ghcr.io/double-nibble/telos-seed
    newTag: latest

patches:
  - path: patch-production.yaml
